[colors]
foreground = "#e5e5ff"
background = "#171719"
cursor_bg = "#e5e5ff"
cursor_border = "#61616A"
cursor_fg = "#171719"
selection_bg = "#2A2A2B"
selection_fg = "#B9B8E3"
split = "#61616A"
compose_cursor = "#ABBDEE"
scrollbar_thumb = "#1F1F21"

ansi = ["#171719", "#BC87A8", "#738980", "#cfa18c", "#87a1e6", "#8a88d1", "#6a969c", "#61616A"]
brights = ["#1F1F21", "#eba9d2", "#90aba0", "#D9B4A3", "#ABBDEE", "#B9B8E3", "#88ABB0", "#e5e5ff"]

[colors.tab_bar]
inactive_tab_edge = "#61616A"
background = "#171719"

[colors.tab_bar.active_tab]
fg_color = "#ABBDEE"
bg_color = "#2A2A2B"

[colors.tab_bar.inactive_tab]
fg_color = "#61616A"
bg_color = "#1F1F21"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#61616A"
bg_color = "#1F1F21"
# intensity = "Bold"

[colors.tab_bar.new_tab_hover]
fg_color = "#ABBDEE"
bg_color = "#2A2A2B"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#ABBDEE"
bg_color = "#171719"

[metadata]
aliases = []
name = "iceclimber"
url = "https://wezfurlong.org/wezterm/config/files.html"
upstream = "https://github.com/cdmill/neomodern.nvim/raw/main/extras/"
author = "Casey Miller"
