[colors]
foreground = "#A2A2AD"
background = "#151515"
cursor_bg = "#A2A2AD"
cursor_border = "#4c4c57"
cursor_fg = "#151515"
selection_bg = "#282828"
selection_fg = "#6d748c"
split = "#4c4c57"
compose_cursor = "#C3C3D0"
scrollbar_thumb = "#1D1D1D"

ansi = ["#1D1D1D", "#8F7352", "#5F645F", "#918F84", "#626E85", "#676068", "#575D70", "#616168"]
brights = ["#4c4c57", "#b39066", "#777d77", "#b5b3a5", "#7a8aa6", "#817882", "#6d748c", "#A2A2AD"]

[colors.tab_bar]
inactive_tab_edge = "#616168"
background = "#151515"

[colors.tab_bar.active_tab]
fg_color = "#C3C3D0"
bg_color = "#282828"

[colors.tab_bar.inactive_tab]
fg_color = "#4c4c57"
bg_color = "#1D1D1D"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#4c4c57"
bg_color = "#1D1D1D"
# intensity = "Bold"

[colors.tab_bar.new_tab_hover]
fg_color = "#C3C3D0"
bg_color = "#282828"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#C3C3D0"
bg_color = "#151515"

[metadata]
aliases = []
name = "moon"
url = "https://wezfurlong.org/wezterm/config/files.html"
upstream = "https://github.com/cdmill/neomodern.nvim/raw/main/extras/"
author = "Casey Miller"
