[colors]
foreground = "#e0def4"
background = "#141517"
cursor_bg = "#e0def4"
cursor_border = "#6e6a86"
cursor_fg = "#141517"
selection_bg = "#27282A"
selection_fg = "#9bbdb8"
split = "#6e6a86"
compose_cursor = "#A3BDD9"
scrollbar_thumb = "#1C1D1F"

ansi = ["#141517", "#c2748b", "#7C9793", "#ebbcba", "#96aff2", "#8E79A7", "#6591bf", "#6e6a86"]
brights = ["#1C1D1F", "#CE90A2", "#9bbdb8", "#c9aa95", "#8E79A7", "#b197d1", "#A3BDD9", "#e0def4"]

[colors.tab_bar]
inactive_tab_edge = "#6e6a86"
background = "#141517"

[colors.tab_bar.active_tab]
fg_color = "#A3BDD9"
bg_color = "#27282A"

[colors.tab_bar.inactive_tab]
fg_color = "#6e6a86"
bg_color = "#1C1D1F"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#6e6a86"
bg_color = "#1C1D1F"
# intensity = "Bold"

[colors.tab_bar.new_tab_hover]
fg_color = "#A3BDD9"
bg_color = "#27282A"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#A3BDD9"
bg_color = "#141517"

[metadata]
aliases = []
name = "roseprime"
url = "https://wezfurlong.org/wezterm/config/files.html"
upstream = "https://github.com/cdmill/neomodern.nvim/raw/main/extras/"
author = "Casey Miller"
