# name: roseprime colors for alacritty
# url: https://github.com/alacritty/alacritty
# upstream: https://github.com/cdmill/neomodern.nvim/raw/main/extras/
# author: Casey Miller

# Default colors
[colors.primary]
background = '#141517'
foreground = '#e0def4'

#[colors.cursor]
#cursor = '#e0def4'
#text = '#141517'

# Normal colors
[colors.normal]
black = '#141517'
red = '#c2748b'
green = '#7C9793'
yellow = '#ebbcba'
blue = '#96aff2'
magenta = '#8E79A7'
cyan = '#6591bf'
white = '#6e6a86'

# Bright colors
[colors.bright]
black = '#1C1D1F'
red = '#CE90A2'
green = '#9bbdb8'
yellow = '#c9aa95'
blue = '#8E79A7'
magenta = '#b197d1'
cyan = '#A3BDD9'
white = '#e0def4'
