# name: iceclimber colors for foot
# url: https://codeberg.org/dnkl/foot
# upstream: https://github.com/cdmill/neomodern.nvim/raw/main/extras/
# author: Casey Miller

[colors]
cursor=e5e5ff 2A2A2B
foreground=e5e5ff
background=171719
selection-foreground=e5e5ff
selection-background=2A2A2B
urls=87a1e6

regular0=171719
regular1=BC87A8
regular2=738980
regular3=cfa18c
regular4=87a1e6
regular5=8a88d1
regular6=6a969c
regular7=61616A

bright0=1F1F21
bright1=eba9d2
bright2=90aba0
bright3=D9B4A3
bright4=ABBDEE
bright5=B9B8E3
bright6=88ABB0
bright7=e5e5ff

16=ABBDEE
