# name: roseprime colors for foot
# url: https://codeberg.org/dnkl/foot
# upstream: https://github.com/cdmill/neomodern.nvim/raw/main/extras/
# author: Casey Miller

[colors]
cursor=e0def4 27282A
foreground=e0def4
background=141517
selection-foreground=e0def4
selection-background=27282A
urls=96aff2

regular0=141517
regular1=c2748b
regular2=7C9793
regular3=ebbcba
regular4=96aff2
regular5=8E79A7
regular6=6591bf
regular7=6e6a86

bright0=1C1D1F
bright1=CE90A2
bright2=9bbdb8
bright3=c9aa95
bright4=8E79A7
bright5=b197d1
bright6=A3BDD9
bright7=e0def4

16=A3BDD9
