# name: moon colors for hyprland
# url: https://github.com/hyprwm/Hyprland                        
# upstream: https://github.com/cdmill/neomodern.nvim/raw/main/extras/              
# author: Casey Miller               

# 1. copy into ~/.config/hypr/
# 2. include at the top of your hyprland.conf:
#       source=~/.config/hypr/moon.conf
# 3. use colors in your hyprland.conf, e.g.:
#       non-alpha:  $COLOR (e.g. $func) 
#       alpha:      rgba($COLORAlpha<transparency> 
#                   (e.g. rgba($funcAlphaee) 

$alt = rgb(C3C3D0)
$altAlpha = C3C3D0

$bg = rgb(151515)
$bgAlpha = 151515

$comment = rgb(4c4c57)
$commentAlpha = 4c4c57

$constant = rgb(b5b3a5)
$constantAlpha = b5b3a5

$fg = rgb(A2A2AD)
$fgAlpha = A2A2AD

$func = rgb(626E85)
$funcAlpha = 626E85

$keyword = rgb(7a8aa6)
$keywordAlpha = 7a8aa6

$line = rgb(1D1D1D)
$lineAlpha = 1D1D1D

$number = rgb(b39066)
$numberAlpha = b39066

$operator = rgb(575D70)
$operatorAlpha = 575D70

$property = rgb(817882)
$propertyAlpha = 817882

$string = rgb(777d77)
$stringAlpha = 777d77

$type = rgb(6d748c)
$typeAlpha = 6d748c

$visual = rgb(282828)
$visualAlpha = 282828

$diag_red = rgb(DC827B)
$diag_redAlpha = DC827B

$diag_blue = rgb(849EE1)
$diag_blueAlpha = 849EE1

$diag_yellow = rgb(AF9974)
$diag_yellowAlpha = AF9974

$diag_green = rgb(69896F)
$diag_greenAlpha = 69896F
