# name: roseprime colors for hyprland
# url: https://github.com/hyprwm/Hyprland                        
# upstream: https://github.com/cdmill/neomodern.nvim/raw/main/extras/              
# author: Casey Miller               

# 1. copy into ~/.config/hypr/
# 2. include at the top of your hyprland.conf:
#       source=~/.config/hypr/roseprime.conf
# 3. use colors in your hyprland.conf, e.g.:
#       non-alpha:  $COLOR (e.g. $func) 
#       alpha:      rgba($COLORAlpha<transparency> 
#                   (e.g. rgba($funcAlphaee) 

$alt = rgb(A3BDD9)
$altAlpha = A3BDD9

$bg = rgb(141517)
$bgAlpha = 141517

$comment = rgb(6e6a86)
$commentAlpha = 6e6a86

$constant = rgb(96aff2)
$constantAlpha = 96aff2

$fg = rgb(e0def4)
$fgAlpha = e0def4

$func = rgb(b197d1)
$funcAlpha = b197d1

$keyword = rgb(6591bf)
$keywordAlpha = 6591bf

$line = rgb(1C1D1F)
$lineAlpha = 1C1D1F

$number = rgb(ebbcba)
$numberAlpha = ebbcba

$operator = rgb(8E79A7)
$operatorAlpha = 8E79A7

$property = rgb(c2748b)
$propertyAlpha = c2748b

$string = rgb(c9aa95)
$stringAlpha = c9aa95

$type = rgb(9bbdb8)
$typeAlpha = 9bbdb8

$visual = rgb(27282A)
$visualAlpha = 27282A

$diag_red = rgb(DF7C82)
$diag_redAlpha = DF7C82

$diag_blue = rgb(89A5F0)
$diag_blueAlpha = 89A5F0

$diag_yellow = rgb(B99B78)
$diag_yellowAlpha = B99B78

$diag_green = rgb(6A8E75)
$diag_greenAlpha = 6A8E75
