# vim:ft=kitty

# name: iceclimber colors for kitty
# url: https://sw.kovidgoyal.net/kitty/conf.html
# upstream: https://github.com/cdmill/neomodern.nvim/raw/main/extras/
# author: Casey Miller

background #171719
foreground #e5e5ff
selection_background #2A2A2B
selection_foreground #e5e5ff
url_color #87a1e6
cursor #e5e5ff
cursor_text_color #171719

# Tabs
active_tab_background #2A2A2B
active_tab_foreground #ABBDEE
inactive_tab_background #1F1F21
inactive_tab_foreground #1F1F21
#tab_bar_background #171719

# Windows
active_border_color #ABBDEE
inactive_border_color #61616A

# normal
color0 #171719
color1 #BC87A8
color2 #738980
color3 #cfa18c
color4 #87a1e6
color5 #8a88d1
color6 #6a969c
color7 #61616A

# bright
color8 #1F1F21
color9 #eba9d2
color10 #90aba0
color11 #D9B4A3
color12 #ABBDEE
color13 #B9B8E3
color14 #88ABB0
color15 #e5e5ff
