# vim:ft=kitty

# name: moon colors for kitty
# url: https://sw.kovidgoyal.net/kitty/conf.html
# upstream: https://github.com/cdmill/neomodern.nvim/raw/main/extras/
# author: Casey Miller

background #151515
foreground #A2A2AD
selection_background #282828
selection_foreground #A2A2AD
url_color #626E85
cursor #A2A2AD
cursor_text_color #151515

# Tabs
active_tab_background #282828
active_tab_foreground #C3C3D0
inactive_tab_background #1D1D1D
inactive_tab_foreground #4c4c57
#tab_bar_background #151515

# Windows
active_border_color #C3C3D0
inactive_border_color #4c4c57

# normal
color0 #1D1D1D
color1 #8F7352
color2 #5F645F
color3 #918F84
color4 #626E85
color5 #676068
color6 #575D70
color7 #616168

# bright
color8 #4c4c57
color9 #b39066
color10 #777d77
color11 #b5b3a5
color12 #7a8aa6
color13 #817882
color14 #6d748c
color15 #A2A2AD
