# vim:ft=kitty

# name: roseprime colors for kitty
# url: https://sw.kovidgoyal.net/kitty/conf.html
# upstream: https://github.com/cdmill/neomodern.nvim/raw/main/extras/
# author: Casey Miller

background #141517
foreground #e0def4
selection_background #27282A
selection_foreground #e0def4
url_color #96aff2
cursor #e0def4
cursor_text_color #141517

# Tabs
active_tab_background #27282A
active_tab_foreground #A3BDD9
inactive_tab_background #1C1D1F
inactive_tab_foreground #1C1D1F
#tab_bar_background #141517

# Windows
active_border_color #A3BDD9
inactive_border_color #6e6a86

# normal
color0 #141517
color1 #c2748b
color2 #7C9793
color3 #ebbcba
color4 #96aff2
color5 #8E79A7
color6 #6591bf
color7 #6e6a86

# bright
color8 #1C1D1F
color9 #CE90A2
color10 #9bbdb8
color11 #c9aa95
color12 #8E79A7
color13 #b197d1
color14 #A3BDD9
color15 #e0def4
