# vim:ft=kitty

# name: roseprime colors for kitty
# url: https://sw.kovidgoyal.net/kitty/conf.html
# upstream: https://github.com/cdmill/neomodern.nvim/raw/main/extras/
# author: Casey Miller

background #15151a
foreground #C5B6C6
selection_background #28282C
selection_foreground #C5B6C6
url_color #788CC2
cursor #C5B6C6
cursor_text_color #15151a

# Tabs
active_tab_background #28282C
active_tab_foreground #9FB6D0
inactive_tab_background #1D1D22
inactive_tab_foreground #${grey}
#tab_bar_background #15151a

# Windows
active_border_color #9FB6D0
inactive_border_color #67606A

# normal
color0 #1D1D22
color1 #9D777D
color2 #7C9793
color3 #A18877
color4 #788CC2
color5 #8583BC
color6 #4C6B8D
color7 #766D77

# bright
color8 #67606A
color9 #c4959c
color10 #9bbdb8
color11 #c9aa95
color12 #96aff2
color13 #a6a4eb
color14 #5f86b0
color15 #C5B6C6

# extended colors
color16 #${alt_bg}
color17 #9FB6D0
